name: OpenAI

on:
    issue_comment: 
        types: [created]
permissions: 
    pull-requests: write
jobs:
    chat:
        runs-on: ubuntu-latest
        steps:
            - name: Debug Comment Body
              run: echo "${{ github.event.comment.body }}"
            - uses: ca-dp/code-butler@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}